FROM alpine:latest
MAINTAINER Adrian Dvergsdal [atmoz.net]

# Steps done in one RUN layer:
# - Install packages
# - OpenSSH needs /var/run/sshd to run
# - Remove generic host keys, entrypoint generates unique keys
RUN echo "@community http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && \
    apk add --no-cache bash shadow@community openssh openssh-sftp-server && \
    mkdir -p /var/run/sshd && \
    rm -f /etc/ssh/ssh_host_*key*

COPY files/sshd_config /etc/ssh/sshd_config
COPY files/ssh_host_ed25519_key /etc/ssh/ssh_host_ed25519_key
COPY files/ssh_host_ed25519_key.pub /etc/ssh/ssh_host_ed25519_key.pub
COPY files/ssh_host_rsa_key /etc/ssh/ssh_host_rsa_key
COPY files/ssh_host_rsa_key.pub /etc/ssh/ssh_host_rsa_key.pub
COPY files/create-sftp-user /usr/local/bin/
COPY files/entrypoint /

EXPOSE 22

ENTRYPOINT ["/entrypoint"]
